---
- name: "Execute playbook"
  hosts: vagrant_servers
  become: no
  gather_facts: true
  pre_tasks:
    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug:
        var: fact_role_name
        verbosity: 2
    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/site"
    - debug:
        var: fact_role_path
        verbosity: 2
    - debug:
        msg:
          - "path = {{ fact_role_path }}"
          - "home = {{ fact_controller_home }}"
          - "user = {{ fact_controller_user }}"
        verbosity: 0
  roles:
    - ansible-role-vagrant
